haptic_teleop_node:
  # 坐标系设置
  robot_eef_frame: "tool0"
  haptic_base_frame: "haptic_base"

  # 平移控制参数
  translation_scale_x: 25  # X轴缩放因子
  translation_scale_y: 25  # Y轴缩放因子
  translation_scale_z: 25  # Z轴缩放因子

  # 旋转控制参数
  rotation_scale: 3  # 旋转缩放因子

  # 运动限制
  max_velocity: 0.1     # 最大线速度 (m/s)
  max_acceleration: 0.1 # 最大加速度 (m/s^2) 