# ur5e_servo.yaml - moveit_servo的详细配置文件 (最终完美版)
# 补全了所有新版本所需的参数。

servo_server:
  # 1. 通信接口: 定义servo_server如何接收和发送指令
  #-----------------------------------------------------------------
  command_in_type: "speed_units" 
  cartesian_command_in_topic: "/servo_server/delta_twist_cmds" 
  joint_command_in_topic: "/servo_server/delta_joint_cmds"
  
  # [最终修正] 补上缺失的 joint_topic 参数。
  # 即使我们不用关节空间控制，也需要定义这个参数。
  joint_topic: "/joint_states"

  command_out_topic: "/joint_group_vel_controller/command" # Servo将向此话题发布速度指令
  command_out_type: "std_msgs/Float64MultiArray"
  status_topic: "/servo_server/status"

  # 2. MoveIt与坐标系
  #-----------------------------------------------------------------
  move_group_name: "manipulator" 
  planning_frame: "base_link" 
  ee_frame_name: "tool0" 
  robot_link_command_frame: "base_link"

  # 3. 伺服与安全参数
  #-----------------------------------------------------------------
  publish_period: 0.008
  incoming_command_timeout: 0.1 
  low_pass_filter_coeff: 2.0
  lower_singularity_threshold: 17.0 
  hard_stop_singularity_threshold: 30.0 
  joint_limit_margin: 0.1
  
  scale:
    linear: 1.0
    rotational: 1.0
    joint: 1.0

  num_outgoing_halt_msgs_to_publish: 5

  # 4. 碰撞检测
  #-----------------------------------------------------------------
  check_collisions: true
  collision_check_type: "threshold_distance"
  collision_check_rate: 10.0
  self_collision_proximity_threshold: 0.01
  scene_collision_proximity_threshold: 0.02
  min_allowable_collision_distance: 0.01
  collision_distance_safety_factor: 2.0

  # 5. 仿真与其他参数
  #-----------------------------------------------------------------
  use_gazebo: true
  publish_joint_positions: false
  publish_joint_velocities: true
  publish_joint_accelerations: false

# =======================================================
#       新增的速度控制器配置
# =======================================================
# 我们将控制器名称统一为 "joint_group_velocity_controller"
joint_group_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint